feat: trim metadatas (part 2)
vortex-data/vortex pull request #1028
Opened 2024-10-14 17:06 UTC by lwwmanning

now all of the encodings have PTypes instead of DTypes, removed unnecessary lengths, etc.

also renamed e.g., `zigzag.rs` to `array.rs` to standardize the per-encoding file layout

2024-10-14 17:17 UTC, danking requested changes, later dismissed

2024-10-14 17:17 UTC, danking commented on encodings/fsst/src/array.rs
> +        let uncompressed_lengths_ptype = uncompressed_lengths.dtype().try_into()?;
Should we prefer the more explicit `PType::try_from(...)`

2024-10-14 17:17 UTC, danking commented on encodings/runend/src/array.rs
> +        DType::Primitive(self.metadata().ends_ptype, Nullability::NonNullable)
This is `DType::from(self.metadata().ends_ptype)`

2024-10-14 21:35 UTC, robert3005 commented
Somehow you managed to type coerce values in forarray

2024-10-15 01:04 UTC, lwwmanning commented
> Somehow you managed to type coerce values in forarray

FlexBuffers got me, they automatically narrow the integer type when writing, and we don't store the PValue enum type because we assumed they'd round trip (or that we'd cast to the dtype)

https://github.com/spiraldb/vortex/blob/develop/vortex-scalar/src/serde/serde.rs

2024-10-15 07:38 UTC, robert3005 approved these changes

2024-10-15 11:05 UTC, merged