chore: move infer_schema and infer_data_type into vortex-dtype
vortex-data/vortex pull request #1081
Opened 2024-10-17 19:40 UTC by danking

I want to use these in PyVortex without depending on vortex-datafusion.

2024-10-17 19:46 UTC, AdamGS approved these changes, later dismissed

2024-10-17 19:48 UTC, lwwmanning commented on vortex-array/src/arrow/dtype.rs
> +/// # Panics
Stale comment

2024-10-17 19:49 UTC, robert3005 requested changes
We should not standardise this code but instead come up with a solution. This method is wrong but necessary for datafusion. Not quite sure what the flow is in pyarrow but I would like to avoid this method being api. At most we should copy paste it as an implementation of pyvortex

2024-10-17 20:37 UTC, danking commented on vortex-array/src/arrow/dtype.rs
> +/// # Panics
Removed.

2024-10-18 14:18 UTC, danking commented
@robert3005 we now bail on lists

2024-10-18 14:25 UTC, robert3005 commented on vortex-array/src/arrow/dtype.rs
> +        DType::List(..) => vortex_bail!("Unsupported dtype: {}", dtype),
For posterity - we will canonicalize to List View. We should figure out what to do about fixed size lists though

2024-10-18 14:25 UTC, robert3005 approved these changes

2024-10-18 15:57 UTC, merged