[wip] FastLanes bitpacking scalar_at
vortex-data/vortex pull request #160
Opened 2024-03-27 17:25 UTC by lwwmanning

2024-04-02 21:26 UTC, lwwmanning commented
will rebase on #179 once that merges

2024-04-02 22:07 UTC, gatesn requested changes, later dismissed
I think we should benchmark this. There's quite a lot of logic for 1 scalar and I think there's quite a lot of room to improve performance

2024-04-02 22:07 UTC, gatesn commented on fastlanez/src/transpose.rs
> +    assert!(
Can you use const generics to constrain this in the type system?

2024-04-02 22:07 UTC, gatesn commented on fastlanez/src/bitpack.rs
> +    const BYTES_PER_TRANCHE: usize = 128 * W;
We don't really use the word tranche anywhere, maybe just stay consistent and inline 128 * W.

Same for below.

2024-04-03 17:53 UTC, lwwmanning commented
benchmark results at commit https://github.com/fulcrum-so/vortex/pull/160/commits/e88374f630091902b93a8d300197d1d9f28f90e3 on my MacBook Air M2:

```zsh
~/g/vortex ❯❯❯ cargo bench --bench bitpacking
   Compiling vortex-fastlanes v0.1.0 (/Users/will/git/vortex/vortex-fastlanes)
    Finished `bench` profile [optimized] target(s) in 1.83s
     Running benches/bitpacking.rs (target/release/deps/bitpacking-274b666c83950221)
Gnuplot not found, using plotters backend
bitpack_1M              time:   [55.673 µs 55.768 µs 55.883 µs]
Found 13 outliers among 100 measurements (13.00%)
  11 (11.00%) high mild
  2 (2.00%) high severe

unpack_1M               time:   [224.61 µs 240.60 µs 258.08 µs]
Found 11 outliers among 100 measurements (11.00%)
  6 (6.00%) high mild
  5 (5.00%) high severe

unpack_1M_singles       time:   [2.2627 ms 2.2864 ms 2.3125 ms]
Found 13 outliers among 100 measurements (13.00%)
  8 (8.00%) high mild
  5 (5.00%) high severe

unpack_1024             time:   [43.631 ns 43.774 ns 43.928 ns]
Found 3 outliers among 100 measurements (3.00%)
  2 (2.00%) high mild
  1 (1.00%) high severe

unpack_single           time:   [4.9211 ns 4.9358 ns 4.9515 ns]
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild
```

2024-04-03 19:07 UTC, gatesn approved these changes

2024-04-03 19:07 UTC, merged

2024-04-03 23:30 UTC, robert3005 commented on vortex-fastlanes/src/bitpacking/compute.rs
> +    }
This needs to take patches into account