FoR compare
vortex-data/vortex pull request #1656
Opened 2024-12-12 11:15 UTC by gatesn

Fixes #1570 
Fixes #1420 

Needs tests

2024-12-12 11:23 UTC, AdamGS approved these changes

2024-12-12 11:26 UTC, AdamGS requested changes, later dismissed
Please add tests.

2024-12-12 14:14 UTC, doki23 commented on encodings/fastlanes/src/for/compute/compare.rs
> +    // get right regarding how to handle overflow and the wrapping subtraction.
If the right side is less than the reference, we can perform a short-circuit `Greater Than` comparison.

2025-01-07 15:33 UTC, lwwmanning approved these changes

2025-01-07 15:51 UTC, merged