PyVortex
vortex-data/vortex pull request #729
Opened 2024-09-04 19:38 UTC by danking

PyVortex
--------

The generated documentation for this branch is available at https://spiraldb.github.io/vortex/docs/

The Python package is now structured like this:

- `vortex`
  - `array()`: converts a list or an Arrow array into a Vortex array.
  - `encodings`
    - `Array`: In Rust this is called a PyArray and it is just PyO3 wrapper around a Vortex Rust Array. - `to_pandas` - `to_numpy`
    - `compress()`: compresses an Array.
  - `dtype`: A module containing dtype constructors, e.g. `uint(32, nullable=False)`
  - `io`: Readers and writers which currently only work for Struct arrays without top-level nulls.
    - `read()`
    - `write()`
  - `expr` - `Expr`: a class, implemented in Rust, which constructs vortex-exprs using the obvious Python operators.

I also added `python_repr` which returns a Display-able struct that renders itself in the Python `repr` style. In particular, the dtypes look like `uint(32, False)` rather than `u32`.

I think the only bugfixes in this PR are:

1. pyvortex/src/encode.rs: propagate the nullability from Arrow to `Array::from_arrow`.
2. arrow/recordbatch.rs and arrow/dtype.rs need to return compatible nullability and validity.

Future Work
-----------

1. Automatically generate and deploy the documentation to github.io.
2. Run `cd pyvortex/docs && make doctest` on every commit.

2024-09-04 20:34 UTC, a10y commented on pyvortex/src/dtype.rs
> +    fn __repr__(&self) -> String {
we should probably implement equality as well. can be flup

2024-09-04 21:19 UTC, robert3005 commented on vortex-array/src/array/struct_/mod.rs
> +                validity.nullability(),
assign this to the variable and then you don't need to clone

2024-09-04 22:06 UTC, robert3005 requested changes
I think we can move some things around. Creating tokio runtime is a bit annoying but it's a future problem to solve

2024-09-04 22:06 UTC, robert3005 commented on vortex-dtype/src/dtype.rs
> +    pub fn python_repr(&self) -> DTypePythonRepr {
Can we move this to the pyvortex module

2024-09-04 22:06 UTC, robert3005 commented on vortex-dtype/src/extension.rs
> +    }
Move this to the pyvortex module. Basically you'd do `ExtIDPythonRepr { ext_id: self }.to_string()`

2024-09-04 22:06 UTC, robert3005 commented on pyvortex/src/dtype.rs
> +        format!("{}", self.inner.python_repr())
Move the code here?

2024-09-04 22:06 UTC, robert3005 commented on pyvortex/src/io.rs
> +            .collect::<Vec<VortexResult<Array>>>()
```suggestion
            .collect::<VortexResult<Vec<Array>>>()
```

2024-09-04 22:06 UTC, robert3005 commented on pyvortex/src/io.rs
> +            .collect::<Vec<VortexResult<Array>>>()
Then you `.await?`and don't have to collect again

2024-09-04 22:06 UTC, robert3005 commented on pyvortex/src/io.rs
> +            TokioAdapter(file), // TODO(dk): Why didn't we implement this on File directly?
it's trivial to make this work with plain file. Should just add this to the repo by default

2024-09-04 22:06 UTC, robert3005 commented on pyvortex/src/array.rs
> +        // NOTE(robert): Return RecordBatchStreamReader always?
```suggestion
```

2024-09-05 16:37 UTC, danking commented on vortex-array/src/array/struct_/mod.rs
> +                validity.nullability(),
Done.

2024-09-05 16:37 UTC, danking commented on vortex-dtype/src/dtype.rs
> +    pub fn python_repr(&self) -> DTypePythonRepr {
Done. Now located at pyvortex/src/python_repr.rs

2024-09-05 16:37 UTC, danking commented on vortex-dtype/src/extension.rs
> +    }
Done.

2024-09-05 16:37 UTC, danking commented on pyvortex/src/io.rs
> +            .collect::<Vec<VortexResult<Array>>>()
I played a bit of type golf but I can't really figure out why this doesn't work. It seems related to `stream` being an async stream. It seems like the trick is to use `try_collect`:
```
        let vecs: Vec<Array> = stream.try_collect().await?;
```
The errors from `collect`:
```
error[E0277]: the trait bound `Result<Vec<vortex::Array>, VortexError>: Default` is not satisfied
   --> pyvortex/src/io.rs:159:34
    |
159 |         let a = stream.collect::<VortexResult<Vec<Array>>>();
    |                        -------   ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Default` is not implemented for `Result<Vec<vortex::Array>, VortexError>`
    |                        |
    |                        required by a bound introduced by this call
    |
note: required by a bound in `futures::StreamExt::collect`
   --> /Users/danielking/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/mod.rs:522:19
    |
522 |     fn collect<C: Default + Extend<Self::Item>>(self) -> Collect<Self, C>
    |                   ^^^^^^^ required by this bound in `StreamExt::collect`

error[E0277]: the trait bound `Result<Vec<vortex::Array>, VortexError>: Extend<Result<vortex::Array, VortexError>>` is not satisfied
   --> pyvortex/src/io.rs:159:34
    |
159 |         let a = stream.collect::<VortexResult<Vec<Array>>>();
    |                        -------   ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Extend<Result<vortex::Array, VortexError>>` is not implemented for `Result<Vec<vortex::Array>, VortexError>`
    |                        |
    |                        required by a bound introduced by this call
    |
    = help: the following other types implement trait `Extend<A>`:
              `()` implements `Extend<()>`
              `(ExtendA, ExtendB)` implements `Extend<(A, B)>`
              `BTreeMap<K, V, A>` implements `Extend<(&'a K, &'a V)>`
              `BTreeMap<K, V, A>` implements `Extend<(K, V)>`
              `BTreeSet<T, A>` implements `Extend<&'a T>`
              `BTreeSet<T, A>` implements `Extend<T>`
              `BinaryHeap<T, A>` implements `Extend<&'a T>`
              `BinaryHeap<T, A>` implements `Extend<T>`
            and 70 others
note: required by a bound in `futures::StreamExt::collect`
   --> /Users/danielking/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/mod.rs:522:29
    |
522 |     fn collect<C: Default + Extend<Self::Item>>(self) -> Collect<Self, C>
    |                             ^^^^^^^^^^^^^^^^^^ required by this bound in `StreamExt::collect`

error[E0277]: the trait bound `Result<Vec<vortex::Array>, VortexError>: Default` is not satisfied
```

2024-09-05 16:37 UTC, danking commented on pyvortex/src/io.rs
> +            TokioAdapter(file), // TODO(dk): Why didn't we implement this on File directly?
https://github.com/spiraldb/vortex/pull/738

2024-09-05 16:44 UTC, danking commented on pyvortex/src/array.rs
> +        // NOTE(robert): Return RecordBatchStreamReader always?
Done.

2024-09-05 16:45 UTC, danking commented on pyvortex/src/dtype.rs
> +        format!("{}", self.inner.python_repr())
Done.

2024-09-05 17:43 UTC, robert3005 commented on vortex-dtype/src/nullability.rs
> +impl Nullability {}
remove this?

2024-09-05 17:44 UTC, robert3005 commented on pyvortex/src/dtype.rs
> +        format!("{}", self.inner.python_repr())
this can be 
```suggestion
        self.inner.python_repr().to_string()
```

2024-09-05 17:44 UTC, robert3005 approved these changes

2024-09-05 17:46 UTC, danking commented on vortex-dtype/src/nullability.rs
> +impl Nullability {}
Done.

2024-09-05 17:46 UTC, danking commented on pyvortex/src/dtype.rs
> +        format!("{}", self.inner.python_repr())
Done.

2024-09-05 18:01 UTC, merged